apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: goserver-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    name: goserver
    apiVersion: apps/v1
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
